# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Pawsome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase - Using latest versions for Twitter OAuth support
  pod 'Firebase/Auth', '~> 11.0'
  pod 'Firebase/Firestore', '~> 11.0'
  pod 'Firebase/Core', '~> 11.0'

  # Google Sign-In
  pod 'GoogleSignIn', '~> 8.0'

  # CocoaPods Gem dependencies
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end