const firebaseConfig={apiKey:"AIzaSyAtqr3lOWMQxkWmY1kSSmimkaMjeSoXUuo",authDomain:"pawsome-90cb3.firebaseapp.com",projectId:"pawsome-90cb3",storageBucket:"pawsome-90cb3.firebasestorage.app",messagingSenderId:"798924982333"};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore();
const $=id=>document.getElementById(id);
let user=null,userData={},posts=[],filter="",unsubscribe=null,selectedStatus="LOST",selectedFile=null,admin=false;

document.addEventListener("DOMContentLoaded",()=>{
  $("google-login").onclick=()=>login(new firebase.auth.GoogleAuthProvider());
  $("twitter-login").onclick=()=>login(new firebase.auth.TwitterAuthProvider());
  $("logout").onclick=()=>auth.signOut();
  document.querySelectorAll(".nav,.create-btn").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
  document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderFeed()});
  $("mobile-profile").onclick=()=>showTab("profile");
  $("close-image").onclick=()=>$("image-modal").classList.add("hidden");
  auth.onAuthStateChanged(async u=>{user=u;if(u){await ensureUser();await loadAdminClaim();$("auth-screen").classList.add("hidden");$("app").classList.remove("hidden");$("loading").classList.add("hidden");showTab("home");startFeed()}else{$("app").classList.add("hidden");$("auth-screen").classList.remove("hidden");$("loading").classList.add("hidden")}});
});

async function login(provider){$("auth-error").textContent="";try{await auth.signInWithPopup(provider)}catch(e){$("auth-error").textContent=e.message}}
async function ensureUser(){
 const ref=db.collection("users").doc(user.uid),snap=await ref.get();
 if(snap.exists){userData=snap.data();return}
 const counter=db.collection("counter").doc("users");let id=0;
 await db.runTransaction(async t=>{const c=await t.get(counter);id=(c.exists?(c.data().lastUserID||0):0)+1;t.set(counter,{lastUserID:id},{merge:true});t.set(ref,{Username:user.displayName||"User"+id,ProfilePic:user.photoURL||"",UserID:id,LoginMethod:providerName(),JoinedOn:firebase.firestore.FieldValue.serverTimestamp()})});
 userData={Username:user.displayName||"User"+id,ProfilePic:user.photoURL||"",UserID:id};
}
function providerName(){const p=(user.providerData.find(x=>x.providerId!=="firebase")||{}).providerId||"";return p==="google.com"?"Google":p==="twitter.com"?"Twitter":p==="apple.com"?"Apple":"Unknown"}
async function loadAdminClaim(){try{const tok=await user.getIdTokenResult(true);admin=tok.claims.admin===true;document.querySelector(".admin-nav").classList.toggle("hidden",!admin)}catch{admin=false}}
function startFeed(){if(unsubscribe)unsubscribe();unsubscribe=db.collection("posts").orderBy("PostedAt","desc").onSnapshot(s=>{posts=s.docs.map(d=>({id:d.id,...d.data()}));renderFeed()},e=>showToast(e.message))}
function timeAgo(ts){if(!ts?.toDate)return"";let sec=(Date.now()-ts.toDate().getTime())/1000;if(sec<60)return"just now";if(sec<3600)return Math.floor(sec/60)+"m ago";if(sec<86400)return Math.floor(sec/3600)+"h ago";return Math.floor(sec/86400)+"d ago"}
function statusClass(s){return String(s||"").toLowerCase()}
function renderFeed(){const list=filter?posts.filter(p=>p.status===filter):posts;const f=$("feed");if(!list.length){f.innerHTML='<div class="empty"><div class="emoji">😿</div><h2>No cats found</h2><p>Be the first to post!</p></div>';return}f.innerHTML=list.map(postCard).join("")}
function postCard(p){const liked=(p.likes||[]).includes(user.uid);const status=p.status||"LOST";const canDelete=p.UserID===userData.UserID;
return '<article class="post"><div class="post-head"><img class="avatar" src="'+esc(p.ProfilePic||"")+'" onerror="this.src=\'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2244%22 height=%2244%22%3E%3Ccircle cx=%2222%22 cy=%2222%22 r=%2222%22 fill=%22%23eee%22/%3E%3C/svg%3E\'"><div><div class="post-user">'+esc(p.Username||"User")+'<span class="status '+statusClass(status)+'">'+statusEmoji(status)+" "+esc(statusName(status))+'</span></div><div class="meta">'+esc(timeAgo(p.PostedAt))+(p.location?' • 📍 '+esc(p.location):'')+'</div></div><div style="margin-left:auto">'+(canDelete?'<button class="small-danger" onclick="deletePost(\''+p.id+'\',\''+esc(p.imageURL||"")+'\')">Delete</button>':"")+'</div></div><img class="post-image" src="'+esc(p.imageURL||"")+'" alt="'+esc(p.CatName||"Cat")+'" onclick="openImage(\''+esc(p.imageURL||"")+'\')"><div class="post-body"><div class="post-title">'+esc(p.CatName||"Unnamed")+(p.CatAge?'<span class="pill">'+esc(p.CatAge)+' yrs</span>':"")+(p.Breed?'<span class="pill blue">'+esc(p.Breed)+'</span>':"")+'</div>'+(p.description?'<div class="desc">'+esc(p.description)+'</div>':"")+'</div><div class="actions"><button class="like '+(liked?"liked":"")+'" onclick="toggleLike(\''+p.id+'\')">'+(liked?"♥":"♡")+" "+(p.likes||[]).length+" likes</button></div></article>"}
function statusEmoji(s){return s==="FOUND"?"🟢":s==="REUNITED"?"🟡":"🔴"}function statusName(s){return s==="FOUND"?"Found":s==="REUNITED"?"Reunited":"Lost"}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function toggleLike(id){const p=posts.find(x=>x.id===id);if(!p)return;const ref=db.collection("posts").doc(id);await ref.update({likes:(p.likes||[]).includes(user.uid)?firebase.firestore.FieldValue.arrayRemove(user.uid):firebase.firestore.FieldValue.arrayUnion(user.uid)})}
async function deletePost(id){if(!confirm("Delete this post?"))return;try{await db.collection("posts").doc(id).delete();showToast("Post deleted")}catch(e){showToast(e.message)}}
function openImage(url){if(!url)return;$("full-image").src=url;$("image-modal").classList.remove("hidden")}
function showTab(tab){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));document.querySelectorAll(".nav").forEach(v=>v.classList.remove("active"));if(tab==="home"){$("home-view").classList.remove("hidden");document.querySelector('[data-tab="home"]').classList.add("active")}if(tab==="create"){$("create-view").classList.remove("hidden");renderCreate()}if(tab==="profile"){$("profile-view").classList.remove("hidden");document.querySelector('[data-tab="profile"]').classList.add("active");renderProfile()}if(tab==="admin"&&admin){$("admin-view").classList.remove("hidden");document.querySelector('[data-tab="admin"]').classList.add("active");renderAdmin()}}
function renderCreate(){selectedStatus="LOST";selectedFile=null;$("create-view").innerHTML='<div class="form-card"><h2>Create Post</h2><p style="color:#777">Share a lost or found cat with the community.</p><div class="status-grid"><button class="status-choice lost selected" onclick="chooseStatus(\'LOST\')">🔴<br>Lost</button><button class="status-choice found" onclick="chooseStatus(\'FOUND\')">🟢<br>Found</button></div><label class="photo-drop" id="photo-drop"><span>📷<br><b>Add a photo of the cat</b><br><small>JPG, PNG or WebP</small></span><input id="photo" type="file" accept="image/*" hidden onchange="pickPhoto(event)"></label><div class="fields"><label class="field">🐾<input id="cat-name" placeholder="Cat Name"></label><label class="field">🎂<input id="age" inputmode="numeric" maxlength="2" placeholder="Age (years)"></label><label class="field">🐱<input id="breed" placeholder="Breed"><small id="breed-state"></small></label><label class="field">📍<input id="location" placeholder="Location (optional)"></label><label class="field">📝<textarea id="description" placeholder="Description"></textarea></label></div><button id="submit-post" class="submit" disabled onclick="submitPost()">Post 🔴</button></div>';$("photo-drop").onclick=()=>$("photo").click()}
function chooseStatus(s){selectedStatus=s;document.querySelectorAll(".status-choice").forEach(b=>b.classList.remove("selected"));document.querySelector(".status-choice."+s.toLowerCase()).classList.add("selected");$("submit-post").textContent="Post "+statusEmoji(s)}
function pickPhoto(e){selectedFile=e.target.files[0]||null;const drop=$("photo-drop");if(selectedFile){drop.innerHTML='<img src="'+URL.createObjectURL(selectedFile)+'" alt="Selected cat photo"><input id="photo" type="file" accept="image/*" hidden onchange="pickPhoto(event)">';drop.onclick=()=>document.getElementById("photo").click();$("submit-post").disabled=false;detectBreed(selectedFile)}}
async function detectBreed(file){$("breed-state").textContent=" Detecting…";try{const token=await user.getIdToken();const bytes=await file.arrayBuffer();let binary="";const arr=new Uint8Array(bytes);for(let i=0;i<arr.length;i++)binary+=String.fromCharCode(arr[i]);const res=await fetch("https://europe-west1-pawsome-90cb3.cloudfunctions.net/detectCatBreed",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify({data:{imageBase64:btoa(binary),mimeType:file.type||"image/jpeg"}})});const json=await res.json();const breed=json?.data?.breed;if(breed)$("breed").value=breed;$("breed-state").textContent=breed?" ✓ Detected":" (optional)"}catch{$("breed-state").textContent=" (optional)"}} 
async function githubUploadImage(file,filename){const token=await user.getIdToken();const bytes=await file.arrayBuffer();const arr=new Uint8Array(bytes);let binary="";const chunk=0x8000;for(let i=0;i<arr.length;i+=chunk)binary+=String.fromCharCode(...arr.subarray(i,i+chunk));const r=await fetch("https://europe-west1-pawsome-90cb3.cloudfunctions.net/githubUploadImage",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify({data:{imageBase64:btoa(binary),mimeType:file.type||"image/jpeg",filename,folder:"postImages",message:"Upload "+filename}})});const json=await r.json();if(!r.ok||!json?.data?.downloadURL)throw new Error(json?.error?.message||"GitHub image upload failed");return json.data.downloadURL}
async function submitPost(){const name=$("cat-name").value.trim(),age=$("age").value.trim(),desc=$("description").value.trim();if(!name||!age||!desc||!selectedFile)return;const btn=$("submit-post");btn.disabled=true;btn.textContent="Posting…";try{const filename=user.uid+"_"+Date.now()+".jpg";const imageURL=await githubUploadImage(selectedFile,filename);await db.collection("posts").add({CatName:name,CatAge:age,Breed:$("breed").value.trim(),description:desc,location:$("location").value.trim(),status:selectedStatus,imageURL,UserID:userData.UserID,Username:userData.Username,ProfilePic:userData.ProfilePic||"",PostedAt:firebase.firestore.FieldValue.serverTimestamp(),likes:[]});showToast("Post created");showTab("home")}catch(e){showToast("Could not post: "+e.message);btn.disabled=false;btn.textContent="Post "+statusEmoji(selectedStatus)}}
async function renderProfile(){const mine=posts.filter(p=>p.UserID===userData.UserID),likes=posts.reduce((n,p)=>n+(p.likes||[]).includes(user.uid)?n+1:n,0);$("profile-view").innerHTML='<div class="profile-card"><img class="profile-img" src="'+esc(userData.ProfilePic||user.photoURL||"")+'" onerror="this.style.display=\'none\'"><h2>'+esc(userData.Username||"User")+'</h2><p style="color:#777">@'+esc(userData.Username||"user")+'</p><div class="stats"><div class="stat"><strong>'+mine.length+'</strong><span>Posts</span></div><div class="stat"><strong>'+likes+'</strong><span>Likes</span></div><div class="stat"><strong>'+esc(userData.UserID||0)+'</strong><span>Member #</span></div></div><div class="settings"><div class="setting"><strong>🔔 Notifications</strong><small>Manage your notification preferences</small></div><div class="setting"><strong>🐾 My Posts</strong><small>'+mine.length+' posts</small></div><div class="setting"><strong>♥ Liked Posts</strong><small>Posts you have liked</small></div><div class="setting"><strong>ⓘ About Pawsome</strong><small>Version 1.0.0</small></div><div class="setting"><strong>❓ Help & Support</strong><small>Report issues on GitHub</small></div></div><button class="danger" onclick="auth.signOut()">⇥ Log Out</button></div>'}
async function callAdmin(name,data={}){const token=await user.getIdToken();const r=await fetch("https://europe-west1-pawsome-90cb3.cloudfunctions.net/"+name,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify({data})});if(!r.ok)throw new Error(await r.text());return (await r.json()).data||{}}
async function renderAdmin(){if(!admin)return;const v=$("admin-view");v.innerHTML='<div class="admin-card"><h2>Admin</h2><div class="admin-grid"><div class="admin-stat"><span>Posts</span><b id="a-posts">…</b></div><div class="admin-stat"><span>Users</span><b id="a-users">…</b></div></div><h3>Posts</h3><div id="admin-posts" class="admin-list">Loading…</div><h3>App settings</h3><div class="fields"><label class="field">⚙️<input id="announcement-title" placeholder="Announcement title"></label><label class="field">📝<textarea id="announcement-body" placeholder="Announcement message"></textarea></label><label><input id="maintenance" type="checkbox"> Maintenance mode</label><label><input id="ads-enabled" type="checkbox"> Ads enabled</label></div><button class="submit" onclick="saveAdmin()">Save app settings</button><p id="admin-message"></p></div>';try{const [s,p,c]=await Promise.all([callAdmin("adminGetStats"),callAdmin("adminListDocuments",{collectionPath:"posts",limit:100}),callAdmin("adminGetAppConfig")]);$("a-posts").textContent=s.posts||0;$("a-users").textContent=s.users||0;const docs=p.documents||[];$("admin-posts").innerHTML=docs.length?docs.map(x=>'<div class="admin-row"><span><b>'+esc(x.CatName||x.catName||"Untitled")+'</b><br><small>'+esc(x.status||"UNKNOWN")+'</small></span><button class="small-danger" onclick="adminDelete(\''+esc(x.path||"")+'\')">Delete</button></div>').join(""):"No posts found";const f=c.fields||{};$("announcement-title").value=f.announcementTitle||"";$("announcement-body").value=f.announcementBody||"";$("maintenance").checked=!!f.maintenanceMode;$("ads-enabled").checked=f.adsEnabled!==false}catch(e){$("admin-message").textContent=e.message}}
async function adminDelete(path){try{await callAdmin("adminDeleteDocument",{path});renderAdmin()}catch(e){showToast(e.message)}}
async function saveAdmin(){try{await callAdmin("adminSetAppConfig",{fields:{maintenanceMode:$("maintenance").checked,adsEnabled:$("ads-enabled").checked,announcementTitle:$("announcement-title").value,announcementBody:$("announcement-body").value}});showToast("Saved to Firebase")}catch(e){showToast(e.message)}}
function showToast(s){const t=$("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2800)}
window.toggleLike=toggleLike;window.deletePost=deletePost;window.openImage=openImage;window.chooseStatus=chooseStatus;window.pickPhoto=pickPhoto;window.submitPost=submitPost;window.detectBreed=detectBreed;window.adminDelete=adminDelete;window.saveAdmin=saveAdmin;
